/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.DbWork;
import controller.PermitListConfig;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author burak
 */
public class ListPermits extends javax.swing.JFrame {

    
    private int kayitNo;
    private int sicilNo;
    /**
     * Creates new form ListLeaves
     */
    public ListPermits() {
        initComponents();
        init();
    }
    
    private void init(){
        btn_list.setVisible(false); // this button is using for first launch.
        btn_list.doClick();
        
        /**
         * which row is selected? 
         */
        String selectedObject = Integer.toString((int) table_list.getModel().getValueAt(0,0));
        String[] listArray = new DbWork().selectPermitInfo(Integer.parseInt(selectedObject));
        
        
        this.kayitNo = Integer.parseInt(selectedObject);
        lbl_nameSurname.setText(listArray[0]);
        lbl_startTime.setText(listArray[1]);
        lbl_endTime.setText(listArray[2]);
        cmb_Status.setSelectedIndex(Integer.parseInt(listArray[4]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_listType = new javax.swing.JComboBox<>();
        btn_list = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_list = new javax.swing.JTable();
        lbl_startTime = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_endTime = new javax.swing.JLabel();
        cmb_Status = new javax.swing.JComboBox<>();
        btn_saveChange = new javax.swing.JButton();
        lbl_nameSurname = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_userInfo = new javax.swing.JButton();

        setTitle("Permit List");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Permit List");

        cmb_listType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Denied", "Accepted", "Requests" }));
        cmb_listType.setSelectedIndex(2);
        cmb_listType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_listTypeItemStateChanged(evt);
            }
        });
        cmb_listType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_listTypeMouseClicked(evt);
            }
        });

        btn_list.setText("List");
        btn_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listActionPerformed(evt);
            }
        });

        table_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Permit No", "First Name", "Last Name", "Starting Date", "End Date", "Permit Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_listMouseClicked(evt);
            }
        });
        table_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_listKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_list);
        if (table_list.getColumnModel().getColumnCount() > 0) {
            table_list.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        lbl_startTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_startTime.setText("YYYY-MM-DD");

        jLabel3.setText("-");

        lbl_endTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_endTime.setText("YYYY-MM-DD");

        cmb_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reject", "Accept", "Request" }));

        btn_saveChange.setText("Save Changes");
        btn_saveChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveChangeActionPerformed(evt);
            }
        });

        lbl_nameSurname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nameSurname.setText("Name");

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_userInfo.setText("User Information");
        btn_userInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 321, Short.MAX_VALUE)
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_saveChange, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_nameSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_startTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_endTime, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(cmb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cmb_listType, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_list, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_listType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_list))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_startTime)
                    .addComponent(lbl_endTime)
                    .addComponent(lbl_nameSurname)
                    .addComponent(jLabel3))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_saveChange)
                    .addComponent(btn_back)
                    .addComponent(btn_userInfo))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveChangeActionPerformed
        new DbWork().setChangesFromPermits(kayitNo, cmb_Status.getSelectedIndex()); // save changes
        btn_list.doClick();
    }//GEN-LAST:event_btn_saveChangeActionPerformed

    private void table_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_listMouseClicked
        int selectedRowIndex = table_list.getSelectedRow(); // get selected row
        String selectedObject = Integer.toString((int) table_list.getModel().getValueAt(selectedRowIndex,0));
        String[] listArray = new DbWork().selectPermitInfo(Integer.parseInt(selectedObject)); // get selected user info
        
        this.kayitNo = Integer.parseInt(selectedObject);
        lbl_nameSurname.setText(listArray[0]);
        lbl_startTime.setText(listArray[1]);
        lbl_endTime.setText(listArray[2]);
        cmb_Status.setSelectedIndex(Integer.parseInt(listArray[4]));
        this.sicilNo = Integer.parseInt(listArray[5]);
    }//GEN-LAST:event_table_listMouseClicked

    private void cmb_listTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_listTypeMouseClicked
       
    }//GEN-LAST:event_cmb_listTypeMouseClicked

    private void cmb_listTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_listTypeItemStateChanged
        reList(cmb_listType.getSelectedIndex());
        
    }//GEN-LAST:event_cmb_listTypeItemStateChanged

    private void btn_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listActionPerformed
        //for first launch
        reList(cmb_listType.getSelectedIndex());
    }//GEN-LAST:event_btn_listActionPerformed

    private void reList(int choosen){
        /**
         * list table again according to comboBox's value
         */ 
        List<PermitListConfig> leaveList = null;
        DefaultTableModel izintablo = (DefaultTableModel) table_list.getModel();
        izintablo.getDataVector().clear();
        table_list.repaint();

        

        leaveList = new DbWork().getPermitList(choosen);
        Vector[] v = new Vector[leaveList.size()];

        for(int i=0;i<leaveList.size();i++){
            v[i] = new Vector();
            v[i].add(leaveList.get(i).getSicilNo());
            v[i].add(leaveList.get(i).getAd());
            v[i].add(leaveList.get(i).getSoyad());
            v[i].add(leaveList.get(i).getIzinTipi());
            v[i].add(leaveList.get(i).getIzinBaslangic());
            v[i].add(leaveList.get(i).getIzinBitis());
            v[i].add(leaveList.get(i).getDurum());

            izintablo.insertRow(i, v[i]);
        }
    }
    
    
    
    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void table_listKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_listKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_listKeyPressed

    private void btn_userInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userInfoActionPerformed
        UpdateUserAdminPanel update = new UpdateUserAdminPanel(sicilNo);
        update.setVisible(true);
        
    }//GEN-LAST:event_btn_userInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPermits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPermits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPermits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPermits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPermits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_list;
    private javax.swing.JButton btn_saveChange;
    private javax.swing.JButton btn_userInfo;
    private javax.swing.JComboBox<String> cmb_Status;
    private javax.swing.JComboBox<String> cmb_listType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_endTime;
    private javax.swing.JLabel lbl_nameSurname;
    private javax.swing.JLabel lbl_startTime;
    private javax.swing.JTable table_list;
    // End of variables declaration//GEN-END:variables
}
