/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.DbWork;
import controller.UserConfig;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author burak
 */
public class SearchUser extends javax.swing.JFrame {

    /**
     * Creates new form UserSearch
     */
    public SearchUser() {
        initComponents();
        rb_IDNo.setSelected(true); // set selected this at the first launch
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_buttonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_UserInfo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rb_IDNo = new javax.swing.JRadioButton();
        rb_FirstName = new javax.swing.JRadioButton();
        rb_LastName = new javax.swing.JRadioButton();
        rb_all = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tf_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_userInfo = new javax.swing.JButton();

        setTitle("Search User");

        table_UserInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Password", "First Name", "Last Name", "TC ID No", "Gender", "Birthday", "Country", "Unit", "ID No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_UserInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_UserInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_UserInfo);
        if (table_UserInfo.getColumnModel().getColumnCount() > 0) {
            table_UserInfo.getColumnModel().getColumn(4).setPreferredWidth(15);
            table_UserInfo.getColumnModel().getColumn(5).setPreferredWidth(15);
            table_UserInfo.getColumnModel().getColumn(8).setMinWidth(100);
            table_UserInfo.getColumnModel().getColumn(8).setPreferredWidth(100);
            table_UserInfo.getColumnModel().getColumn(9).setPreferredWidth(10);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search User");

        rb_buttonGroup.add(rb_IDNo);
        rb_IDNo.setText("ID No");
        rb_IDNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_IDNoActionPerformed(evt);
            }
        });

        rb_buttonGroup.add(rb_FirstName);
        rb_FirstName.setText("First Name");

        rb_buttonGroup.add(rb_LastName);
        rb_LastName.setText("Last Name");

        rb_buttonGroup.add(rb_all);
        rb_all.setText("All");
        rb_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_allActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Type :");

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_userInfo.setText("User Information");
        btn_userInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_IDNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_FirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_LastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_all)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_search)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_IDNo)
                    .addComponent(rb_FirstName)
                    .addComponent(rb_LastName)
                    .addComponent(jLabel2)
                    .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_all))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search)
                    .addComponent(btn_back)
                    .addComponent(btn_userInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_UserInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_UserInfoMouseClicked
    }//GEN-LAST:event_table_UserInfoMouseClicked

    private void rb_IDNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_IDNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_IDNoActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
            
        /**
         * which radio button is selected?
         */
        
        if (rb_IDNo.isSelected()){
            setIntoTable("sicilNo");
            tf_search.setText("");
        }
        else if(rb_FirstName.isSelected()){
            setIntoTable("ad");
            tf_search.setText("");
        }
        else if(rb_LastName.isSelected()){
            setIntoTable("soyad");
            tf_search.setText("");
            
            
        }else if(rb_all.isSelected()){
            tf_search.setText("");
            setIntoTable(null);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Geçersiz Giriş");
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void rb_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_allActionPerformed
    }//GEN-LAST:event_rb_allActionPerformed

    private void btn_userInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userInfoActionPerformed
        try {
            /**
             * selected column  : 9 
             * selected row     : user will select
             */
            int selectedRowIndex = table_UserInfo.getSelectedRow();
            int selectedUser = (int) table_UserInfo.getModel().getValueAt(selectedRowIndex,9);
            
            UpdateUserAdminPanel selectedUserInfo = new UpdateUserAdminPanel(selectedUser);
            selectedUserInfo.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seçim Yapılmadı");
        }
        
    }//GEN-LAST:event_btn_userInfoActionPerformed

    private void setIntoTable(String query){ // setting into the table all of user datas
        try {
            DefaultTableModel userInfoDefaultTable = (DefaultTableModel) table_UserInfo.getModel();
            userInfoDefaultTable.getDataVector().clear();
            table_UserInfo.repaint();
            
            List<UserConfig> tableContent = new DbWork().getUserInfoTable(query,tf_search.getText());
            
            Vector[] v = new Vector[tableContent.size()];
            
            for(int i =0;i<tableContent.size();i++){
                v[i] = new Vector();
                v[i].add(tableContent.get(i).getKadi());
                v[i].add(tableContent.get(i).getSifre());
                v[i].add(tableContent.get(i).getAd());
                v[i].add(tableContent.get(i).getSoyad());
                v[i].add(tableContent.get(i).getTcNo());
                v[i].add(tableContent.get(i).getCinsiyet());
                v[i].add(tableContent.get(i).getDogumTarihi());
                v[i].add(tableContent.get(i).getSehir());
                v[i].add(tableContent.get(i).getBirimAdi());
                v[i].add(tableContent.get(i).getSicilNo());
                
                
                userInfoDefaultTable.insertRow(i,v[i]);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Message: "+e.getMessage());
        }
    
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_userInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_FirstName;
    private javax.swing.JRadioButton rb_IDNo;
    private javax.swing.JRadioButton rb_LastName;
    private javax.swing.JRadioButton rb_all;
    private javax.swing.ButtonGroup rb_buttonGroup;
    private javax.swing.JTable table_UserInfo;
    private javax.swing.JTextField tf_search;
    // End of variables declaration//GEN-END:variables
}
